# appveyor.yml
build: script
clone_folder: /usr/go/src/github.com/$username/$project

environment:
  GOPATH: /usr/go/

stack: go 1.13

before_test:
  - go vet ./...

test_script:
  - go test ./...
  
build_script:
  - go build
